import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Space Tourism | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <section className="bottom-32 left-0 mx-6 mt-6 flex flex-col items-center justify-between gap-y-30 text-center md:mx-[128px] md:mt-[128px] md:gap-y-16 xl:absolute xl:mx-[165px] xl:flex-row xl:text-left">
        <div className="max-w-[512px] xl:w-1/2 xl:max-w-none">
          <h1>
            <span className="font-main block text-base tracking-widest text-slate-300 md:text-[28px]">
              SO, YOU WANT TO TRAVEL TO
            </span>
            <span className="font-title block text-[80px] md:text-[144px]">
              SPACE
            </span>
          </h1>
          <p className="text-lg">
            Let’s face it; if you want to go to space, you might as well
            genuinely go to outer space and not hover kind of on the edge of it.
            Well sit back, and relax because we’ll give you a truly out of this
            world experience!
          </p>
        </div>
        <button className="font-title h-36 w-36 rounded-full bg-white text-lg tracking-widest text-slate-900 uppercase md:h-59 md:w-59 md:text-[32px]">
          Explore
        </button>
      </section>
    </>
  );
}
