import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Space Tourism | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      {/* <div className="w-full h-full relative"> */}
      <section className="absolute bottom-32 left-0 flex items-center mx-[165px] justify-between">
        <div className="w-1/2">
          <h1 className={`text-[144px] font-title`}>
            <span className="block text-[28px] font-main text-slate-300">
              SO, YOU WANT TO TRAVEL TO
            </span>{" "}
            SPACE
          </h1>
          <p className="text-lg">
            Let’s face it; if you want to go to space, you might as well
            genuinely go to outer space and not hover kind of on the edge of it.
            Well sit back, and relax because we’ll give you a truly out of this
            world experience!
          </p>
        </div>
        <button className="w-59 h-59 bg-white rounded-full text-slate-900 uppercase text-[32px] font-title">
          Explore
        </button>
      </section>
      {/* </div> */}
    </>
  );
}
